

solr_path: /usr/local/share/solr
solr_log_path: /var/log/solr
solr_user: solr
solr_group: solr

cache_path: /tmp/vagrant-cache

# Container folder for solr downloads
#solr_url: http://www.nic.funet.fi/pub/mirrors/apache.org/lucene/solr/
solr_url: ftp://www.nic.funet.fi/pub/mirrors/apache.org/lucene/solr/

# Version
solr_version: 4.7.2
