---
# file: roles/web-front/tasks/php53u.yml
  - name: Install ius archive repository
    shell: rpm -Uhv http://dl.iuscommunity.org/pub/ius/archive/CentOS/6/x86_64/ius-release-1.0-11.ius.centos6.noarch.rpm
      creates=/etc/yum.repos.d/ius-archive.repo

  - name: Enable ius archive repository
    ini_file: dest=/etc/yum.repos.d/ius-archive.repo
              section=ius-archive
              option=enabled
              value=1

# Install all php packages
  - name: Install php-fpm
    yum: pkg={{ php_package }}-fpm state=installed
  - name: Ensure php-fpm is running now and on boot
    service: name=php-fpm state=started enabled=yes
  - name: Install php packages
    yum: pkg={{ item }} state=installed
    with_items:
      - "{{ php_package }}"
      - "{{ php_package }}-mysql"
      - "{{ php_package }}-gd"
      - "{{ php_package }}-imap"
      - "{{ php_package }}-mbstring"
      - "{{ php_package }}-pear"
      - "{{ php_package }}-xml"
      - "{{ php_package }}-xmlrpc"
      - "{{ php_package }}-pdo"
      - "{{ php_package }}-pecl-memcache"
      - "{{ php_package }}-pecl-memcached"
      - "{{ php_package }}-pecl-apc"
      - "{{ php_package }}-devel"
      - "{{ php_package }}-dba"
      - "{{ php_package }}-mcrypt"
      - "{{ php_package }}-soap"
      - "{{ php_package }}-pecl-redis"
      - "{{ php_package }}-suhosin"
