project:
  name: wundertools
ansible:
  remote: https://github.com/wunderkraut/WunderMachina.git
  branch: master
  revision:
buildsh:
  enabled: true
  branch: develop
  revision:
wundertools:
  branch: master
  repository: badrange/WunderTools
externaldrupal:
  remote:
  branch:

