project:
  name: ansibleref
ansible:
  remote: git@github.com:wunderkraut/WunderMachina.git
  branch: centos7
  revision:
buildsh:
  enabled: true
  branch: develop
  revision:
wundertools:
  branch: master
externaldrupal:
  remote:
  branch:

