---

- hosts: vagrant
  become: true
  become_method: sudo
  user: vagrant
  roles:
   - role: common
   - role: cache
   - role: database
   - role: solr
   - role: varnish
   - role: web-front
   - role: drupal
   - role: devtools
   - role: solr_config
