---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  # An alias or aliases for the site, this could also be:
  # aliases:
  #   - vagrant
  #   - mylocalbox
  aliases: vagrant

  # Omit makefile to leave out drush
  # makefile: conf/site.make
  type: composer

  # Directory used to build the site
  temporary: _build

  make_cache: .make_cache

  # The final produced Drupal installation
  final: current

  # The Subpath of "final" and "temporary" where drupal resides.
  drupal_subpath: /web
  # Directory which will house all the previous builds
  previous: builds

  # Installation profile to use
  profile: config_installer

  # Site name given at installation phase
  site: Wundersite

local:
  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - conf/composer/composer.json: composer.json
    - conf/composer/composer.lock: composer.lock
    - files: web/sites/default/files
    - code/modules: web/modules/custom
    - code/themes: web/themes/custom
    - staging: staging

  copy:
    - conf/services.yml: web/sites/default/services.yml
    - conf/settings.php: web/sites/default/settings.php
    - conf/settings.local.php: web/sites/default/settings.local.php
    - conf/composer/autoload.php: web/autoload.php
    - conf/_ping.php: web/_ping.php

stage:

  link:
    - files: web/sites/default/files

  copy:
    - code/modules: web/modules
    - code/themes: web/themes
    - conf/composer/autoload.php: web/autoload.php
    - conf/composer/composer.json: composer.json
    - conf/composer/composer.lock: composer.lock
    - staging: staging
    - conf/settings.php: web/sites/default/settings.php
    - conf/stage.settings.php: web/sites/default/settings.local.php
    - conf/services.yml: web/sites/default/services.yml
    - conf/_ping.php: web/_ping.php

production:

  link:
    - files: web/sites/default/files

  copy:
    - code/modules: web/modules
    - code/themes: web/themes
    - conf/composer/autoload.php: web/autoload.php
    - conf/composer/composer.json: composer.json
    - conf/composer/composer.lock: composer.lock
    - staging: staging
    - conf/settings.php: web/sites/default/settings.php
    - conf/prod.settings.php: web/sites/default/settings.local.php
    - conf/services.yml: web/sites/default/services.yml
    - conf/_ping.php: web/_ping.php
