---

# Default environment is Vagrant:
default:

  aliases: vagrant

  makefile: conf/site.make
  temporary: _build
  final: current
  previous: builds
  profile: wk
  site: Wundersite

  # In development environments we want to use symlinks, note settings.php
  link:
    - files: sites/default/files
    - code/modules/custom: sites/all/modules/custom
    - code/modules/features: sites/all/modules/features
    - code/themes/custom: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/vagrant.settings.php: sites/default/settings.php
    - conf/aliases.drushrc.php: sites/default/aliases.drushrc.php

# Local environment:
local:

  # Local is sometimes used outside of Vagrant boxes, for example with MAMP)
  link:
    - files: sites/default/files
    - code/modules/custom: sites/all/modules/custom
    - code/modules/features: sites/all/modules/features
    - code/themes/custom: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/local.settings.php: sites/default/settings.php
    - conf/aliases.drushrc.php: sites/default/aliases.drushrc.php

# Test environment:
test:

  # Test environment only symlinks files
  link:
    - files: sites/default/files

  # Other files are copied, note settings.php
  copy:
    - code/modules/custom: sites/all/modules/custom
    - code/modules/features: sites/all/modules/features
    - code/themes/custom: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/test.settings.php: sites/default/settings.php


# Production environment:
production:

  aliases: prod

  # Prod environment only symlinks files
  link:
    - files: sites/default/files

  # Other files are copied, note settings.php
  copy:
    - code/modules/custom: sites/all/modules/custom
    - code/modules/features: sites/all/modules/features
    - code/themes/custom: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/prod.settings.php: sites/default/settings.php

# Command sets:
commands:

  # Steps:
  #  - append: conf/robots.txt > current/robots.txt

  # Basic new site functionality
  new:
    - make
    - backup
    - purge
    - finalize
    - install
    - shell: cp conf/_ping.php current


  # Basic site update functionality
  update:
    - make
    - backup
    - finalize
    - update
    - shell: cp conf/_ping.php current

  # This is just an example on how to create custom commands,
  # this will create a .tgz out of the drupal installation without
  # touching the current installation.
  package:
    - make
    - shell: cp conf/_ping.php _build
    - shell: tar cvfz package.tgz _build
    - shell: rm -rf _build

  # An example on how to use create a simple backup command
  # that will skip database and files dir
  backup:
    - backup:
        skip-database: yes
        ignore:
          - sites/default/files

