---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  # An alias or aliases for the site, this could also be:
  # aliases:
  #   - vagrant
  #   - mylocalbox
  aliases: vagrant

  # Omit makefile to leave out drush
  # makefile: conf/site.make
  type: composer

  # Directory used to build the site
  temporary: _build

  make_cache: .make_cache

  # The final produced Drupal installation
  final: current

  # The Subpath of "final" and "temporary" where drupal resides.
  drupal_subpath: /drupal

  # Directory which will house all the previous builds
  previous: builds

  # Installation profile to use
  profile: config_installer

  # Site name given at installation phase
  site: Wundersite

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - conf/composer/composer.json: composer.json
    - files: drupal/sites/default/files
    - code/modules: drupal/modules/custom
    - code/themes: drupal/themes/custom
    - conf/drupal: config
    - conf/local.settings.php: drupal/sites/default/settings.php

  copy:
    - conf/composer/index.php: drupal/index.php
    - conf/composer/autoload.php: drupal/autoload.php

production:

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - code/modules: drupal/modules/custom

  copy:
    - conf/composer/index.php: drupal/index.php
    - conf/composer/autoload.php: drupal/autoload.php
    - conf/composer/composer.json: composer.json
    - files: drupal/sites/default/files
    - code/themes: drupal/themes/custom
    - conf/drupal: config
    - conf/local.settings.php: drupal/sites/default/settings.php


